import streamlit as st

# Define the Streamlit app
def app():
    st.title("[ About ]")

    # About the Project Section
    st.header("**The Project**")
    st.info("📝 Originally developed in **2024** for the GovTech AI Bootcamp on Google Vertex AI; **revised in 2026** to use a vendor-neutral Bring Your Own Key (BYOK) architecture.")
    st.markdown("""
This project was developed for learning purposes as the final assignment for the GovTech AI Bootcamp under the Project B category, with the aim of addressing real challenges in the construction industry.
Below are some of the considerations outlined for this project.

<div style="color:#4FC3F7;">
<strong>2026 update:</strong> the problem framing, target users, and outputs are unchanged — the bootcamp's learning goals remain the founding context. What changed is the implementation: the original Vertex AI + Google Cloud Storage pipeline has been migrated to a provider-neutral BYOK architecture via LiteLLM (<code>parsers/byo_agent.py</code>). Visitors now run the agents on their own free-tier or paid key from Gemini, OpenAI, Groq, or Mistral — no GCP project, billing, or service account required.
</div>

**Key Question**:

- How can we simplify and automate repetitive checks, reduce non-compliance risks, and improve workflows to ease the work burden on project stakeholders?
  (referencing [AI Hackathon](https://www.aihackathon.pro/winners) topic 1)

**Objective**:

- Develop a scalable Proof of Concept (PoC) using a common building component to demonstrate how an AI-powered solution can automate repetitive checks, reduce non-compliance risks, and minimize manual workloads.
- <span style="color:#4FC3F7"><strong>2026 extension:</strong> "scalable" now also means scalable across <strong>inference providers</strong>. The same agent code runs unchanged on any LiteLLM-supported model, so the PoC can scale outward to new models as they emerge without re-platforming.</span>

**Scope**:

- Use a window schedule as the design intent to check for compliance with relevant BCA-approved documents and SCDF Chapter 4 requirements.

**Benefits**:

- **Work Efficiency**: Simplifies understanding of regulatory requirements, speeding up design processes.
- **Reduced Manual Effort**: Automates design checks, providing real-time guidance and feedback.
- **Scalability**: Modular functions allow for continuous updates and further development.
- <span style="color:#4FC3F7"><strong>Vendor Neutrality (2026 revision):</strong> visitors run live inference with their own free-tier or paid API key from Gemini, OpenAI, Groq, or Mistral. No vendor lock-in, no project billing exposure, no service-account distribution — and the choice of provider lives in the user's hands.</span>

**Strategies**:

- **AI-Driven Workflow**: Use AI tools and language models to improve efficiency and accuracy in compliance checks.
- <s style="color:#888"><strong>Simple Data Hosting</strong>: Store non-sensitive data on Google Cloud Storage (GCS) and GitHub for scalable and easy cloud setup.</s><br><span style="color:#4FC3F7"><strong>Local & Bring-Your-Own-Key (BYOK) Hosting</strong>: All input/output files are bundled in the GitHub repo — no cloud storage needed. Live AI runs use the visitor's own free-tier or paid API key via LiteLLM, so the PoC costs the project zero in inference fees.</span>
- **Fast Web Development**: Use Streamlit for quick, interactive website creation to enhance user experience.

**Data**:

- **Input**: Window schedules (JPEG format), BCA-approved documents, and SCDF Fire Code 2023 Chapter 4 (PDF format).
- **Output**: Processed documents and recommendations (XLS and/or TXT formats) generated by AI models.

**Features**:

- <s style="color:#888"><strong>AI-Driven Parsing</strong>: Automated extraction and tabulation of design requirements using Google AI model Gemini-1.5-Pro-002.</s><br><span style="color:#4FC3F7"><strong>AI-Driven Parsing (BYOK, multi-provider)</strong>: Multimodal vision extraction of design requirements. Visitors choose their provider — <strong>Gemini, OpenAI, Groq, or Mistral</strong> — and the same code path runs on any LiteLLM-supported vision model. No GCP credentials required.</span>
- **Data Analysis & Recommendations**: AI-powered data processing to analyze compliance and generate design recommendations.
- <s style="color:#888"><strong>Interactive Validation Interface</strong>: Real-time regulatory checks using OpenAI's GPT-4o-Mini model for enhanced user interaction.</s><br><span style="color:#4FC3F7"><strong>Interactive Validation Interface (BYOK)</strong>: Real-time regulatory checks across all 5 agents using the visitor's own API key. Gemini and Groq offer free tiers; OpenAI and Mistral are paid. The visitor's key is sent only to the chosen provider and is never stored or logged.</span>
- <span style="color:#4FC3F7"><strong>Shared BYOK module</strong> (<code>parsers/byo_agent.py</code>): a single LiteLLM-backed wrapper that handles vision input (Agents 1-2), PDF text extraction via PyPDF2 (Agents 3-5), pinned prompts, and provider-agnostic completion calls. Swapping providers is a one-string model change. The three legacy Vertex AI / GCS scripts are preserved in <code>parsers/archived/</code> for reference.</span>
    """, unsafe_allow_html=True)

    st.header("**Who are we?**")
    
    col1, col2 = st.columns(2)

    # Use markdown for links since link_button is not a valid function
    with col1:
        st.image("https://github.com/integrations-space/streamlit/raw/main/pictures/ww.jpg", width=100) 
        st.write("Mr. PONG Woon Wei (Lead)")
        st.markdown("[LinkedIn Profile](https://www.linkedin.com/in/woonwei/)")  
        st.write("Explore the use of AI agents for automatic data parsing, analysis, and reporting to improve and streamline checking processes [gemini-1.5-pro-002]")
        st.markdown("[aianalyser.streamlit.app](https://aianalyser.streamlit.app/)")  


    with col2:
        st.image("https://github.com/integrations-space/streamlit/raw/main/pictures/unni.jpg", width=100) 
        st.write("Mr. Unni Krishnan AMBADY")
        st.markdown("[LinkedIn Profile](https://www.linkedin.com/in/unni-krishnan-ambady-0287a4164)")
        st.write("Explore the use of the OpenAI model as an independent interactive validator to verify generated outputs [gpt-4o-mini]")
        st.markdown("[bca-project.streamlit.app](https://bca-project.streamlit.app/)") 
        
# Run the app if the script is executed directly
if __name__ == "__main__":
    # Use st.set_page_config to ensure the page is properly configured
    st.set_page_config(page_title="About Us", page_icon="📋", layout="wide")
    app()